/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraivan;

import java.awt.Color;

/**
 *
 * @author zgame
 */
public class VtnPrincipal extends javax.swing.JFrame {

    String numero1;
    String numero2;
    String signo;
    
    public VtnPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        
        colorearBotones();
        
        txtPantalla.setOpaque(false);
    }
    
    public void colorearBotones()
    {
        botonBorrar.setBackground(Color.white);
        botonBorrarTodo.setBackground(Color.white);
        botonCero.setBackground(Color.white);
        botonCinco.setBackground(Color.white);
        botonCuatro.setBackground(Color.white);
        botonDivision.setBackground(Color.white);
        botonDos.setBackground(Color.white);
        
        botonIgual.setBackground(Color.cyan);
        
        botonMultiplicacion.setBackground(Color.white);
        botonNueve.setBackground(Color.white);
        botonOcho.setBackground(Color.white);
        botonResta.setBackground(Color.white);
        botonSeis.setBackground(Color.white);
        botonSiete.setBackground(Color.white);
        botonSigno.setBackground(Color.white);
        botonSuma.setBackground(Color.white);
        botonTres.setBackground(Color.white);
        botonUno.setBackground(Color.white);
        botonPunto.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonPunto = new javax.swing.JButton();
        botonDos = new javax.swing.JButton();
        botonNueve = new javax.swing.JButton();
        botonSeis = new javax.swing.JButton();
        botonTres = new javax.swing.JButton();
        botonOcho = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        botonCinco = new javax.swing.JButton();
        botonSiete = new javax.swing.JButton();
        botonUno = new javax.swing.JButton();
        botonCuatro = new javax.swing.JButton();
        botonCero = new javax.swing.JButton();
        botonMultiplicacion = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        botonSuma = new javax.swing.JButton();
        txtPantalla = new javax.swing.JTextField();
        botonBorrar = new javax.swing.JButton();
        botonBorrarTodo = new javax.swing.JButton();
        botonSigno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonPunto.setText(".");
        botonPunto.setPreferredSize(new java.awt.Dimension(75, 25));
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        getContentPane().add(botonPunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 70, 30));

        botonDos.setText("2");
        botonDos.setPreferredSize(new java.awt.Dimension(75, 30));
        botonDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDosActionPerformed(evt);
            }
        });
        getContentPane().add(botonDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 70, -1));

        botonNueve.setText("9");
        botonNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNueveActionPerformed(evt);
            }
        });
        getContentPane().add(botonNueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 70, 30));

        botonSeis.setText("6");
        botonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeisActionPerformed(evt);
            }
        });
        getContentPane().add(botonSeis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 70, 30));

        botonTres.setText("3");
        botonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTresActionPerformed(evt);
            }
        });
        getContentPane().add(botonTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 70, 30));

        botonOcho.setText("8");
        botonOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOchoActionPerformed(evt);
            }
        });
        getContentPane().add(botonOcho, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, 30));

        botonIgual.setText("=");
        botonIgual.setBorder(null);
        botonIgual.setPreferredSize(new java.awt.Dimension(75, 25));
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        getContentPane().add(botonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 50, 30));

        botonCinco.setText("5");
        botonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCincoActionPerformed(evt);
            }
        });
        getContentPane().add(botonCinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 70, 30));

        botonSiete.setText("7");
        botonSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSieteActionPerformed(evt);
            }
        });
        getContentPane().add(botonSiete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 30));

        botonUno.setText("1");
        botonUno.setMaximumSize(new java.awt.Dimension(70, 30));
        botonUno.setMinimumSize(new java.awt.Dimension(70, 30));
        botonUno.setPreferredSize(new java.awt.Dimension(70, 30));
        botonUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUnoActionPerformed(evt);
            }
        });
        getContentPane().add(botonUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));

        botonCuatro.setText("4");
        botonCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuatroActionPerformed(evt);
            }
        });
        getContentPane().add(botonCuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 30));

        botonCero.setText("0");
        botonCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCeroActionPerformed(evt);
            }
        });
        getContentPane().add(botonCero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 70, 30));

        botonMultiplicacion.setText("X");
        botonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(botonMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 50, 30));

        botonResta.setText("-");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        getContentPane().add(botonResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 50, 30));

        botonDivision.setText("/");
        botonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(botonDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 50, 30));

        botonSuma.setText("+");
        botonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumaActionPerformed(evt);
            }
        });
        getContentPane().add(botonSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 50, 30));

        txtPantalla.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPantalla.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPantalla.setBorder(null);
        txtPantalla.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPantalla.setEnabled(false);
        txtPantalla.setOpaque(false);
        txtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 290, 40));

        botonBorrar.setText("<<");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 30));

        botonBorrarTodo.setText("CE");
        botonBorrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(botonBorrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, 30));

        botonSigno.setText("+/-");
        botonSigno.setPreferredSize(new java.awt.Dimension(75, 25));
        botonSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSignoActionPerformed(evt);
            }
        });
        getContentPane().add(botonSigno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 40, 20));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaActionPerformed

    private void botonUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUnoActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"1");
    }//GEN-LAST:event_botonUnoActionPerformed

    private void botonCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCeroActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"0");
    }//GEN-LAST:event_botonCeroActionPerformed

    private void botonDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDosActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"2");
    }//GEN-LAST:event_botonDosActionPerformed

    private void botonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTresActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"3");
    }//GEN-LAST:event_botonTresActionPerformed

    private void botonCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuatroActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"4");
    }//GEN-LAST:event_botonCuatroActionPerformed

    private void botonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCincoActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"5");
    }//GEN-LAST:event_botonCincoActionPerformed

    private void botonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeisActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"6");
    }//GEN-LAST:event_botonSeisActionPerformed

    private void botonSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSieteActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"7");
    }//GEN-LAST:event_botonSieteActionPerformed

    private void botonOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOchoActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"8");
    }//GEN-LAST:event_botonOchoActionPerformed

    private void botonNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNueveActionPerformed
        txtPantalla.setText(txtPantalla.getText()+"9");
    }//GEN-LAST:event_botonNueveActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        String pantalla; //almacena todo lo que tiene la pantalla
        pantalla=txtPantalla.getText();
        
        if (pantalla.length()<=0) 
        {
            txtPantalla.setText("0.");
        }
        else
        {
            if (!punto(txtPantalla.getText())) 
            {
                txtPantalla.setText(txtPantalla.getText()+".");
            }
        }
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        String s;
        
        s=txtPantalla.getText();
        
        if (s.length()>0) 
        {
            s = s.substring(0,s.length()-1);
        }
        
        txtPantalla.setText(s);
        
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonBorrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarTodoActionPerformed
        txtPantalla.setText("");
    }//GEN-LAST:event_botonBorrarTodoActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        if (!txtPantalla.getText().equals("")) 
        {
            numero1=txtPantalla.getText();
            signo="-";
            txtPantalla.setText("");
            
        }
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumaActionPerformed
        if (!txtPantalla.getText().equals("")) 
        {
            numero1=txtPantalla.getText();
            signo="+";
            txtPantalla.setText("");
            
        }
    }//GEN-LAST:event_botonSumaActionPerformed

    private void botonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicacionActionPerformed
        if (!txtPantalla.getText().equals("")) 
        {
            numero1=txtPantalla.getText();
            signo="*";
            txtPantalla.setText("");
            
        }
    }//GEN-LAST:event_botonMultiplicacionActionPerformed

    private void botonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivisionActionPerformed
        if (!txtPantalla.getText().equals("")) 
        {
            numero1=txtPantalla.getText();
            signo="/";
            txtPantalla.setText("");
            
        }
    }//GEN-LAST:event_botonDivisionActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        String resultado;
        numero2=txtPantalla.getText();
        
        if (!numero2.equals("")) 
        {
            resultado=calculadora(numero1,numero2,signo);
            txtPantalla.setText(resultado);
        }
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSignoActionPerformed
        Double num;
        String cadena;
        
        cadena=txtPantalla.getText();
        
        if (cadena.length()>0) 
        {
            num=(-1)*Double.parseDouble(cadena);
            txtPantalla.setText(num.toString());
        }
    }//GEN-LAST:event_botonSignoActionPerformed

    
    public static String calculadora(String numero1,String numero2,String signo)
    {
        Double resultado=0.0;
        String respuesta;
        
        if (signo.equals("-")) 
        {
            resultado=Double.parseDouble(numero1)-Double.parseDouble(numero2);
        }
        
        if (signo.equals("+")) 
        {
            resultado=Double.parseDouble(numero1)+Double.parseDouble(numero2);
        }
        
        if (signo.equals("/")) 
        {
            resultado=Double.parseDouble(numero1)/Double.parseDouble(numero2);
        }
        
        if (signo.equals("*")) 
        {
            resultado=Double.parseDouble(numero1)*Double.parseDouble(numero2);
        }
        
        respuesta=resultado.toString();
        return respuesta;
    }
    
    public static boolean punto(String s)
    {
        boolean resultado=false;
        
        for (int i = 0; i < s.length(); i++) 
        {
            if (s.substring(i,i+1).equals(".")) 
            {
                resultado=true;
                break;
            }
        }
        return resultado;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBorrarTodo;
    private javax.swing.JButton botonCero;
    private javax.swing.JButton botonCinco;
    private javax.swing.JButton botonCuatro;
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonDos;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMultiplicacion;
    private javax.swing.JButton botonNueve;
    private javax.swing.JButton botonOcho;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSeis;
    private javax.swing.JButton botonSiete;
    private javax.swing.JButton botonSigno;
    private javax.swing.JButton botonSuma;
    private javax.swing.JButton botonTres;
    private javax.swing.JButton botonUno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtPantalla;
    // End of variables declaration//GEN-END:variables
}
