/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author yo mero palomero
 */
public class Calculadoraf extends javax.swing.JFrame {

    /**
     * Creates new form Calculadoraf
     */
    public Calculadoraf() {
        initComponents();
    }
    String s;
    float a, b;
    char o;
    boolean i;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLP = new javax.swing.JLabel();
        B0 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        BP = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        BI = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        Bm = new javax.swing.JButton();
        BME = new javax.swing.JButton();
        BX = new javax.swing.JButton();
        BE = new javax.swing.JButton();
        BC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));

        JLP.setBackground(new java.awt.Color(0, 153, 255));
        JLP.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JLP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JLP.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        JLP.setOpaque(true);

        B0.setBackground(new java.awt.Color(51, 102, 255));
        B0.setText("0");
        B0.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B0.setMaximumSize(new java.awt.Dimension(41, 23));
        B0.setMinimumSize(new java.awt.Dimension(41, 23));
        B0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B0MouseClicked(evt);
            }
        });

        B1.setBackground(new java.awt.Color(51, 102, 255));
        B1.setText("1");
        B1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B1.setMaximumSize(new java.awt.Dimension(41, 23));
        B1.setMinimumSize(new java.awt.Dimension(41, 23));
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });

        B7.setBackground(new java.awt.Color(51, 102, 255));
        B7.setText("7");
        B7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B7.setMaximumSize(new java.awt.Dimension(41, 23));
        B7.setMinimumSize(new java.awt.Dimension(41, 23));
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });

        B4.setBackground(new java.awt.Color(51, 102, 255));
        B4.setText("4");
        B4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B4.setMaximumSize(new java.awt.Dimension(41, 23));
        B4.setMinimumSize(new java.awt.Dimension(41, 23));
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });

        BP.setBackground(new java.awt.Color(51, 102, 255));
        BP.setText(".");
        BP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BP.setMaximumSize(new java.awt.Dimension(41, 23));
        BP.setMinimumSize(new java.awt.Dimension(41, 23));
        BP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BPMouseClicked(evt);
            }
        });

        B2.setBackground(new java.awt.Color(51, 102, 255));
        B2.setText("2");
        B2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B2.setMaximumSize(new java.awt.Dimension(41, 23));
        B2.setMinimumSize(new java.awt.Dimension(41, 23));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        B5.setBackground(new java.awt.Color(51, 102, 255));
        B5.setText("5");
        B5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B5.setMaximumSize(new java.awt.Dimension(41, 23));
        B5.setMinimumSize(new java.awt.Dimension(41, 23));
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });

        B9.setBackground(new java.awt.Color(51, 105, 255));
        B9.setText("9");
        B9.setActionCommand("8");
        B9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B9.setMaximumSize(new java.awt.Dimension(41, 23));
        B9.setMinimumSize(new java.awt.Dimension(41, 23));
        B9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B9MouseClicked(evt);
            }
        });

        BI.setBackground(new java.awt.Color(51, 102, 255));
        BI.setText("=");
        BI.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BIMouseClicked(evt);
            }
        });

        B3.setBackground(new java.awt.Color(51, 102, 255));
        B3.setText("3");
        B3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B3.setMaximumSize(new java.awt.Dimension(41, 23));
        B3.setMinimumSize(new java.awt.Dimension(41, 23));
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });

        B6.setBackground(new java.awt.Color(51, 102, 255));
        B6.setActionCommand("6");
        B6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B6.setLabel("6");
        B6.setMaximumSize(new java.awt.Dimension(41, 23));
        B6.setMinimumSize(new java.awt.Dimension(41, 23));
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });

        B8.setBackground(new java.awt.Color(51, 102, 255));
        B8.setText("8");
        B8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        B8.setMaximumSize(new java.awt.Dimension(41, 23));
        B8.setMinimumSize(new java.awt.Dimension(41, 23));
        B8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B8MouseClicked(evt);
            }
        });
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });

        Bm.setBackground(new java.awt.Color(51, 102, 255));
        Bm.setText("+");
        Bm.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Bm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BmMouseClicked(evt);
            }
        });

        BME.setBackground(new java.awt.Color(51, 102, 255));
        BME.setText("-");
        BME.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BME.setMaximumSize(new java.awt.Dimension(41, 23));
        BME.setMinimumSize(new java.awt.Dimension(41, 23));
        BME.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BMEMouseClicked(evt);
            }
        });

        BX.setBackground(new java.awt.Color(51, 102, 255));
        BX.setText("X");
        BX.setActionCommand("6");
        BX.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BX.setMaximumSize(new java.awt.Dimension(41, 23));
        BX.setMinimumSize(new java.awt.Dimension(41, 23));
        BX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BXMouseClicked(evt);
            }
        });

        BE.setBackground(new java.awt.Color(51, 102, 255));
        BE.setText("/");
        BE.setActionCommand("8");
        BE.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BE.setMaximumSize(new java.awt.Dimension(41, 23));
        BE.setMinimumSize(new java.awt.Dimension(41, 23));
        BE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BEMouseClicked(evt);
            }
        });

        BC.setBackground(new java.awt.Color(51, 102, 255));
        BC.setText("CE");
        BC.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BX, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(BE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(BC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(BC, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BX, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BME, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B0, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BP, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BI, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bm, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B8ActionPerformed

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        if(i)
        {
            JLP.setText(JLP.getText()+'1');
        }else
        {
            JLP.setText("1");
            i=true;
        }

    }//GEN-LAST:event_B1MouseClicked

    private void BmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BmMouseClicked
        s= JLP.getText();
        if(!(s.length()==0))
        {
          a=Float.parseFloat(s);
          o='+';
          JLP.setText("");
        }
        
    }//GEN-LAST:event_BmMouseClicked

    private void BIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BIMouseClicked
        s=JLP.getText();
        if(s.length()>0)
        {
            b=Float.parseFloat(s);
            switch(o)
            {
                case '+': a=a+b;
                         JLP.setText(entero(a));
                break;
                case '-': a=a-b;
                        JLP.setText(entero(a));
                break;
                case 'x': a=a*b;
                    JLP.setText(entero(a));
                break;
                case '/': a=a/b;
                    JLP.setText(entero(a));
                break;
                
            }
            i=false;
            a=0;
            b=0;
        }
        
       
    }//GEN-LAST:event_BIMouseClicked

    private void BPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BPMouseClicked
       if(!(JLP.getText().contains(".")))
       {
           s=JLP.getText();
           s=s+'.';
           JLP.setText(s);
       }
       
    }//GEN-LAST:event_BPMouseClicked

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        if(i)
        {
            JLP.setText(JLP.getText()+'2');
        }else
        {
            JLP.setText("2");
            i=true;
        }
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        if(i)
        {
            JLP.setText(JLP.getText()+'3');
        }else
        {
            JLP.setText("3");
            i=true;
        }
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
       if(i)
        {
            JLP.setText(JLP.getText()+'4');
        }else
        {
            JLP.setText("4");
            i=true;
        }   
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        if(i)
        {
            JLP.setText(JLP.getText()+'5');
        }else
        {
            JLP.setText("5");
            i=true;
        }
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        if(i)
        {
            JLP.setText(JLP.getText()+'6');
        }else
        {
            JLP.setText("6");
            i=true;
        }
    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
        if(i)
        {
            JLP.setText(JLP.getText()+'7');
        }else
        {
            JLP.setText("7");
            i=true;
        }
    }//GEN-LAST:event_B7MouseClicked

    private void B8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B8MouseClicked
       if(i)
        {
            JLP.setText(JLP.getText()+'8');
        }else
        {
            JLP.setText("8");
            i=true;
        }
    }//GEN-LAST:event_B8MouseClicked

    private void B9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B9MouseClicked
       if(i)
        {
            JLP.setText(JLP.getText()+'9');
        }else
        {
            JLP.setText("9");
            i=true;
        }
    }//GEN-LAST:event_B9MouseClicked

    private void B0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B0MouseClicked
        if(i)
        {
            JLP.setText(JLP.getText()+'0');
        }else
        {
            JLP.setText("0");
            i=true;
        }
    }//GEN-LAST:event_B0MouseClicked

    private void BMEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BMEMouseClicked
        s= JLP.getText();
        if(!(s.length()==0))
        {
          a=Float.parseFloat(s);
          o='-';
          JLP.setText("");  
        }
    }//GEN-LAST:event_BMEMouseClicked

    private void BXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BXMouseClicked
        s= JLP.getText();
        if(!(s.length()==0))
        {
          a=Float.parseFloat(s);
          o='x';
          JLP.setText(""); 
        }
    }//GEN-LAST:event_BXMouseClicked

    private void BEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BEMouseClicked
        s= JLP.getText();
        if(!(s.length()==0))
        {
          a=Float.parseFloat(s);
          o='/';
          JLP.setText("");  
        }
    }//GEN-LAST:event_BEMouseClicked

    private void BCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCMouseClicked
        JLP.setText("");
        a=0;
        b=0;
    }//GEN-LAST:event_BCMouseClicked

    /**
     * @param args the command line arguments
     */
    public String entero(float r)
    {
        String l;
        l=Float.toString(r);
        if(r%1==0)
        {
            l=l.substring(0, l.length()-2);
        }
        return l;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadoraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadoraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadoraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadoraf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadoraf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B0;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton BC;
    private javax.swing.JButton BE;
    private javax.swing.JButton BI;
    private javax.swing.JButton BME;
    private javax.swing.JButton BP;
    private javax.swing.JButton BX;
    private javax.swing.JButton Bm;
    private javax.swing.JLabel JLP;
    // End of variables declaration//GEN-END:variables
}
